export const S = {
  APP_NAME: 'your-events',
  APP_TAGLINE: 'Odkryj wydarzenia w Szczecinie',
  NAV_HOME: 'Strona główna',
  NAV_EVENTS: 'Wydarzenia',
  SEARCH_PLACEHOLDER: 'Szukaj wydarzeń...',
  SEARCH_LABEL: 'Szukaj wydarzeń',
  FILTER_TITLE: 'Filtry',
  FILTER_CLEAR: 'Wyczyść filtry',
  FILTER_APPLY: 'Zastosuj',
  FILTER_CATEGORIES: 'Kategorie',
  FILTER_SOURCE: 'Źródło',
  FILTER_DATE: 'Data',
  FILTER_DATE_SINGLE: 'Jeden dzień',
  FILTER_DATE_RANGE: 'Zakres dat',
  FILTER_DATE_FROM: 'Od',
  FILTER_DATE_TO: 'Do',
  FILTER_HOUR: 'Godzina',
  FILTER_HOUR_DISABLED: 'Wybierz najpierw datę',
  FILTER_AGE: 'Wiek',
  FILTER_LEVEL: 'Poziom',
  FILTER_FREE_ONLY: 'Tylko bezpłatne',
  FILTER_HIDE_UNAVAILABLE: 'Ukryj niedostępne',
  VIEW_GRID: 'Widok siatki',
  VIEW_LIST: 'Widok listy',
  PAGE_SIZE_LABEL: 'Na stronie',
  RESULTS_COUNT: (n: number) => `Znaleziono ${n} wydarzeń`,
  RESULTS_PAGE: (page: number, total: number) => `Strona ${page} z ${total}`,
  EMPTY_TITLE: 'Nie znaleziono wydarzeń',
  EMPTY_SUBTITLE: 'Spróbuj zmienić filtry lub wybrać inny zakres dat',
  ERROR_TITLE: 'Coś poszło nie tak',
  ERROR_SUBTITLE: 'Nie udało się pobrać wydarzeń',
  RETRY: 'Spróbuj ponownie',
  BACK: 'Wróć',
  PRICE_FREE: 'Bezpłatne',
  PRICE_UNKNOWN: 'Cena w opisie',
  STATUS_ACTIVE: 'Dostępne',
  STATUS_FEW: 'Ostatnie miejsca',
  STATUS_SOLD: 'Brak miejsc',
  STATUS_CANCELLED: 'Odwołane',
  EXTERNAL_LINK: 'Przejdź do strony',
  FOOTER_SOURCES: 'Źródła danych',
  FOOTER_PRIVACY: 'Polityka prywatności',
  FOOTER_CONTACT: 'Kontakt',
  FOOTER_COPYRIGHT: (year: number) => `© ${year} your-events`,
  AGE_ALL: 'Wszyscy',
  AGE_ADULTS: 'Dorośli',
  AGE_KIDS: 'Dzieci',
  AGE_SENIORS: 'Seniorzy',
  LEVEL_ALL: 'Każdy poziom',
  LEVEL_BEGINNER: 'Początkujący',
  LEVEL_INTERMEDIATE: 'Średniozaawansowany',
  LEVEL_ADVANCED: 'Zaawansowany',
  LEVEL_OPEN: 'Otwarty',
  SKIP_TO_CONTENT: 'Przejdź do treści',
  FILTER_TRIGGER: (n: number) => `Filtry (${n})`,
  DETAIL_DATE: 'Data',
  DETAIL_TIME: 'Godzina',
  DETAIL_LOCATION: 'Lokalizacja',
  DETAIL_CATEGORIES: 'Kategorie',
  DETAIL_TAGS: 'Tagi',
  DETAIL_PRICE: 'Cena',
  DETAIL_AGE: 'Wiek',
  DETAIL_LEVEL: 'Poziom',
  DETAIL_INSTRUCTOR: 'Prowadzący',
  DETAIL_CAPACITY: 'Pojemność',
  DETAIL_RECURRENCE: 'Powtarzalność',
  DETAIL_SOURCE: 'Źródło',
  DETAIL_DESCRIPTION: 'Opis',
  RECURRENCE_WEEKLY: 'Co tydzień',
  RECURRENCE_BIWEEKLY: 'Co dwa tygodnie',
  RECURRENCE_MONTHLY: 'Co miesiąc',
  META_EVENTS_TITLE: 'Wydarzenia w Szczecinie',
  META_DESCRIPTION: 'Odkryj najlepsze wydarzenia w Szczecinie — taniec, fitness, warsztaty kulinarne, koncerty i więcej.',
  LOADING: 'Ładowanie...',
} as const;
